import React from "react";

const CellularImageAnalysisPage = () => {
    return (
        <div>
            <h3> Bioimage Informatics </h3>
            <p> 
                Bioimage Informatics is a specialized subfield of bioinformatics that focuses on the analysis, interpretation, and visualization of biological data derived from images. It integrates advanced computational techniques, image processing, machine learning, and statistical analysis to extract meaningful biological insights from complex image data, such as those generated by microscopes, medical imaging devices, and high-throughput screening technologies. 
            </p>
            <h5> Tumour Detection </h5>
            <p> [To be developed] </p>
            <h5> Cell Culture Flask Confluency Determination Tool </h5>
            <p> [To be developed] </p>
        </div>
    );
};

export default CellularImageAnalysisPage;